### ISSUE TITLE
Plugin failing to load

### ISSUE THREAD

**Issue by jtwurth** [0x4a616e/homebridge-smartthings-ac#3]
**Describe Your Problem:**
After installing your plugin and restarting Homebridge it fails to load.

**Logs:**

```
[8/3/2021, 8:28:20 AM] ====================
[8/3/2021, 8:28:20 AM] ERROR LOADING PLUGIN homebridge-smartthings-ac:
[8/3/2021, 8:28:20 AM] Error: Cannot find module 'hap-nodejs/dist/lib/definitions'
Require stack:
- /usr/local/lib/node_modules/homebridge-smartthings-ac/dist/platformAccessory.js
- /usr/local/lib/node_modules/homebridge-smartthings-ac/dist/platform.js
- /usr/local/lib/node_modules/homebridge-smartthings-ac/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings-ac/src/platformAccessory.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[8/3/2021, 8:28:20 AM] ====================
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge 7839",
        "username": 
        "port": 51947,
        "pin": 
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Home Alarm",
            "auth": {
                "username":
                "password": 
            },
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "excludedDevices": [
                "00641345"
            ],
            "_bridge": {
                "username": 
                "port": 53845
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
        {
            "email": 
            "password": 
            "name": "Garage",
            "platform": "myQ",
            "_bridge": {
                "username": 
                "port": 31943
            }
        },
        {
            "token": "a68ccd6f-3a09-4461-b3d2-d490f40e4f5f",
            "minTemperature": 16,
            "maxTemperature": 30,
            "updateInterval": 15,
            "platform": "HomebridgeSmartThingsAC"
        }
    ]
}
                                                                                                                                         
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0.7
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.16.1
* **NPM Version**: 6.14.12
* **Operating System**: macOS 11.5.1

**Comment by 0x4a616e** [comment]
Looks like hap library is missing. Does running
`sudo npm install -g hap-nodejs` solve the issue?

**Comment by TondaRuzicka** [comment]
FYI Installed the plugin and I had the same issue. Your solution above worked. Thanks a lot. I finally have my AC in homekit. It's amazing! :)

**Comment by 0x4a616e** [comment]
Thanks for sharing! I actually haven't found out _why_ this library is sometimes missing... It is, however, not recommended to include hap in the dependencies of the plugin because that would more or less mean to include another homebridge in the dependencies. Thus, i'm not sure how this problem could be solved within this project.

**Comment by appel** [comment]
Hey 0x4a616e, thank you so much for this plugin. Sorry for resurrecting this old thread, but I'm having the same issue and running `sudo npm install -g hap-nodejs` inside the docker container sadly did not fix it in my case.

I'm running homebridge-smartthings-ac in Homebridge 1.3.9 on a Raspberry pi 4. Restarted homebridge and the container and reinstalled the plugin, but no dice. I've include the logs below. Do you have some pointers for me in terms of what I could try to resolve it?

```
1/17/2022, 12:39:43 PM] ====================
[1/17/2022, 12:39:43 PM] ERROR LOADING PLUGIN homebridge-smartthings-ac:
[1/17/2022, 12:39:43 PM] Error: Cannot find module 'hap-nodejs/dist/lib/definitions'
Require stack:
- /homebridge/node_modules/homebridge-smartthings-ac/dist/platformAccessory.js
- /homebridge/node_modules/homebridge-smartthings-ac/dist/platform.js
- /homebridge/node_modules/homebridge-smartthings-ac/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-smartthings-ac/src/platformAccessory.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[1/17/2022, 12:39:43 PM] ====================
```

**Comment by 0x4a616e** [comment]
Hi, good question... I googled a bit for similar issues and the solution always seems to be to manually install hap-nodejs. Unfortunately, I still don't understand why this is sometimes happening, so I really don't have any better idea... The only thing I can possibly imagine is that it's some sort of version issue. I can try publishing a new version with updated dependencies, maybe this helps. I'm in fact still using homebridge@1.3.4 and hap-nodejs@0.9.4 so there are definitely some updates available...

**Comment by appel** [comment]
Thanks Jan, I appreciate it. I'll keep an eye on the repo, perhaps it'll resolve itself when versions bump in the future.

**Comment by 0x4a616e** [comment]
@appel i just upgraded all dependencies and pushed a new version. maybe this helps 🤞
